### PR TITLE
doc:improved

### PR DESCRIPTION
**Pull request by heysagnik**

### CODE REVIEW

**Comment by heysagnik** [comment]
@JideGuru why did you closed the PR

**Comment by JideGuru** [comment]
Hi, sorry I think I closed it by mistake. I wanted to leave a comment.
Can you center the title and undo the other changes? I'll approve your PR after that. I'll like to retain the badges and emojis

thanks

**Comment by heysagnik** [comment]
> Hi, sorry I think I closed it by mistake. I wanted to leave a comment. Can you center the title and undo the other changes? I'll approve your PR after that. I'll like to retain the badges and emojis
> 
> thanks


The title is already centered

**Comment by JideGuru** [comment]
Great. Please undo the other changes

**Pull request closed without merging**
